language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t jrunning/docker-react-video-player -f Dockerfile.dev . 

# script:
#   - docker run -e CI=true jrunning/docker-react-video-player npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-video-player"
  env: "Dockerreactvideoplayer-env"
  bucket_name: "elasticbeanstalk-us-east-1-531836388365"

  
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY